#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# run terraform fmt
terraform fmt --recursive
terraform validate

# run terragrunt fmt
terragrunt hclfmt --terragrunt-diff
terragrunt hclfmt 

# terragrunt run-all validate

# run other smoke or acceptance tests etc
