#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# run terraform fmt
terraform fmt --recursive
terraform validate

# run terragrunt fmt
terragrunt hclfmt --terragrunt-diff
terragrunt hclfmt 

# will fail if run by GitHub Desktop due to not assuming AWS IAM role
# will fail if run from non leaf-level dir (i.e. root dir)
# terragrunt run-all validate

# run other smoke or acceptance tests etc
